### ISSUE TITLE
Allow Comments

### ISSUE THREAD

**Issue by esatterwhite** [syntax-tree/hast-util-sanitize#11]
I see in the tests, that it removes comments, but I'd actaully like to keep comments. Is there an option for it, or how would I be able to do that?

I added 
```javascript
{
  comment: {value: handleValue}
}
```

in the node schema and that seems to do what I want. Not sure if that is ideal or if there is a better place for it.

**Comment by wooorm** [comment]
Hmm, that’s funky! a) why? and b) how should we do this?

**Comment by esatterwhite** [comment]
Well I want comments in the html basically.
I'm using HAST to generate html documents from user input via JSON api. So in translating to html, its exceptionally helpful to use html comments to debug.

I use this package to remove scripts, clean up html, etc. But it's also removing my comment markers.


```javascript
{
   "type": "conversation"
  , ... options
}
```
```html
<!-- START BLOCK CONVERSATION -->
   ... 3000 lines of generated html
<!-- END BLOCK CONVERSATION -->
```
That is all I'm really after. 

I have a fork, where i did this
```html
const NODES = {
  root: {children: all}
, element: {
    tagName: handleTagName
  , properties: handleProperties
  , children: all
  }
, text: {value: handleValue}
, comment: {value: handleValue}
, '*': {
    data: allow
  , position: allow
  }
}
```

that allows them, just not sure if that is the most efficient thing? of if you know of a better way?

**Comment by wooorm** [comment]
@esatterwhite Are you into writing a PR for this?
