### ISSUE TITLE
toPropertyValueMap fails if the value is undefined

### ISSUE THREAD

**Issue by sebglow** [syntax-tree/hast-util-sanitize#14]
The link to the line of code that causes error:  [https://github.com/syntax-tree/hast-util-sanitize/commit/ba16c1591d0769489f62bcdac946dd7a8e4f71d9#r32393248](https://github.com/syntax-tree/hast-util-sanitize/commit/ba16c1591d0769489f62bcdac946dd7a8e4f71d9#r32393248)

**Comment by ChristianMurphy** [comment]
@sebglow Do you have an example of content that will fail that you could share? Would you be interested in opening a PR to resolve the issue?

**Comment by sebglow** [comment]
Hi. Thank you for the response.
At this moment I don't have any example. The error originates inside the
patternplate (1.7.4) which we use in our project.
I'll try to extract some code to reproduce the issue -  but I cannot
promise I'll be able to do that soon :(

Best regards
Sebastian



śr., 20 lut 2019 o 17:07 Christian Murphy <notifications@github.com>
napisał(a):

**Comment by wooorm** [comment]
This error can occur if the used schema at attributes is not of the proper type. For example:

```js
{
  // ...
  "attributes": {
    "div": "className"
    // ...
  },
  // ...
}
```

[The docs state that the value per tag name should be an array](https://github.com/syntax-tree/hast-util-sanitize#attributes), so the code is acting as documented and the schema (used in patternplate?) should be fixed!
