### ISSUE TITLE
Allow raw nodes to remain (optionally)

### ISSUE THREAD

**Issue by erquhart** [syntax-tree/hast-util-sanitize#9]
I'd like the safety of sanitization using this plugin, but I need to alter what node types are ignored. This could be a part of schema extension, perhaps, where we can pass an array of node types to ignore, or an array of ignored types to allow.

Thoughts?

**Comment by wooorm** [comment]
I feel weird about that: If you’d allow `raw` nodes, you’re allowing any of the HTML in it to slip through `sanitize`?

**Comment by erquhart** [comment]
Ah, maybe I should be reparsing?

**Comment by erquhart** [comment]
Yep, that's the ticket! Thanks :)

**Comment by wooorm** [comment]
Yup this it! 👍
